### ISSUE TITLE
Serial killer and WH = 1 FPS

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_sk#1]
У большинства игроков слабые компьютеры и от WH серийного убийцы у них становится очень низкий FPS, поэтому я предлагаю сделать настройку как клиентскую в F1, чтоб человек мог включить и выключить, так и серверную, чтоб изначально была выключена и игрок сам включал для себя, если ему нужна.

**Comment by Alf21** [comment]
Hmm i could do this, but this would break the sense of the serialkiller. Instead, don‘t use this add-on. But I will try to create an own drawing function, maybe this will fix the fps issue...

**Comment by Histalek** [comment]
As the Serial Killer is using a different implementation for the 'wallhack' now and there were no complaints for about half a year im closing this issue.

Feel free to reopen or open a new issue if this particular problem persists.
